### ISSUE TITLE
translation-not-found everywhere

### ISSUE THREAD

**Issue by paulvi** [jhipster/jhipster-sample-app-vuejs#2]
The sample is currently just messed over missing en.json or something else...

![image](https://user-images.githubusercontent.com/1614482/57189227-64203a80-6f3e-11e9-8320-6079eb935304.png)

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-sample-app-vuejs/commit/fbd1509ec23e97c1532287f7d36042546ec49770
